# Generated by Django 6.1.2 on 2026-10-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_autor_categoria_alter_livro_autor_livro_categorias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Autores'},
        ),
    ]
